# Generated by Django 6.0.3 on 2026-03-18 14:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('tables', '0003_rename_cell_type_historicaltablecell_data_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The display title of the form shown to users', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions shown at the top of the form', null=True)),
                ('requires_login', models.BooleanField(default=True, help_text='If True, only authenticated (logged in) users can access and submit this form')),
                ('is_published', models.BooleanField(default=False, help_text='If True, the form is live and accessible to users')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="The section heading displayed to the user e.g. 'Personal Details'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional sub-heading or instructions shown under the section title', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this section within the form (top to bottom)')),
                ('form', models.ForeignKey(help_text='The form this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms.form')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalForm',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(help_text='The display title of the form shown to users', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions shown at the top of the form', null=True)),
                ('requires_login', models.BooleanField(default=True, help_text='If True, only authenticated (logged in) users can access and submit this form')),
                ('is_published', models.BooleanField(default=False, help_text='If True, the form is live and accessible to users')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical form',
                'verbose_name_plural': 'historical forms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormField',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('label', models.CharField(help_text="The field label displayed to the user e.g. 'First Name'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this field. Ordered within its section, or within the form if no section is assigned.')),
                ('is_required', models.BooleanField(default=False, help_text='If True, the user must fill in this field before submitting')),
                ('help_text', models.TextField(blank=True, help_text='Optional helper text shown below the field to guide the user', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('data_source', models.ForeignKey(blank=True, db_constraint=False, help_text='Required for choice-based and relational field types: dropdown, radio, checkbox_multi, multi_select, foreign_key, many_to_many', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.datasource')),
                ('data_type', models.ForeignKey(blank=True, db_constraint=False, help_text='The type of input to render for this field', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.datatype')),
                ('form', models.ForeignKey(blank=True, db_constraint=False, help_text='The form this field belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms.form')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, db_constraint=False, help_text='The section this field belongs to. Leave blank for ungrouped fields', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms.formsection')),
                ('table', models.ForeignKey(blank=True, db_constraint=False, help_text='Required when field_type is table_dynamic or table_fixed', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tables.table')),
            ],
            options={
                'verbose_name': 'historical form field',
                'verbose_name_plural': 'historical form fields',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFormSection',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(help_text="The section heading displayed to the user e.g. 'Personal Details'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional sub-heading or instructions shown under the section title', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this section within the form (top to bottom)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('form', models.ForeignKey(blank=True, db_constraint=False, help_text='The form this section belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms.form')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical form section',
                'verbose_name_plural': 'historical form sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="The field label displayed to the user e.g. 'First Name'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this field. Ordered within its section, or within the form if no section is assigned.')),
                ('is_required', models.BooleanField(default=False, help_text='If True, the user must fill in this field before submitting')),
                ('help_text', models.TextField(blank=True, help_text='Optional helper text shown below the field to guide the user', null=True)),
                ('data_source', models.ForeignKey(blank=True, help_text='Required for choice-based and relational field types: dropdown, radio, checkbox_multi, multi_select, foreign_key, many_to_many', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to='data.datasource')),
                ('data_type', models.ForeignKey(help_text='The type of input to render for this field', on_delete=django.db.models.deletion.CASCADE, to='data.datatype')),
                ('form', models.ForeignKey(help_text='The form this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
                ('table', models.ForeignKey(blank=True, help_text='Required when field_type is table_dynamic or table_fixed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to='tables.table')),
                ('section', models.ForeignKey(blank=True, help_text='The section this field belongs to. Leave blank for ungrouped fields', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='forms.formsection')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
                'unique_together': {('form', 'label')},
            },
        ),
    ]
