# Generated by Django 6.0.3 on 2026-03-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={},
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='updated',
        ),
        migrations.AlterField(
            model_name='datatype',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='HistoricalDataType',
        ),
    ]
