# Generated by Django 6.0.3 on 2026-03-19 09:54

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='draft', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the form was submitted')),
                ('response', models.JSONField(blank=True, default=dict, help_text="The complete submission response stored as structured JSON. Grouped by section. Ungrouped fields sit under 'ungrouped'. See model docstring for full structure reference.")),
                ('form', models.ForeignKey(help_text='The form that was submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFormSubmission',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(default='draft', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp of when the form was submitted')),
                ('response', models.JSONField(blank=True, default=dict, help_text="The complete submission response stored as structured JSON. Grouped by section. Ungrouped fields sit under 'ungrouped'. See model docstring for full structure reference.")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('form', models.ForeignKey(blank=True, db_constraint=False, help_text='The form that was submitted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms.form')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical form submission',
                'verbose_name_plural': 'historical form submissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
