# Generated by Django 6.0.3 on 2026-03-18 10:14

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name for this table e.g. 'Employment History Table'", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this table captures', null=True)),
                ('table_type', models.CharField(choices=[('dynamic_rows', 'Dynamic Rows'), ('fixed_grid', 'Fixed Grid')], default='dynamic_rows', help_text='Whether users can add rows freely or the grid is fixed by the admin', max_length=20)),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTable',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, help_text="Human-readable name for this table e.g. 'Employment History Table'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this table captures', null=True)),
                ('table_type', models.CharField(choices=[('dynamic_rows', 'Dynamic Rows'), ('fixed_grid', 'Fixed Grid')], default='dynamic_rows', help_text='Whether users can add rows freely or the grid is fixed by the admin', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical table',
                'verbose_name_plural': 'historical tables',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTableRow',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('row_label', models.CharField(help_text="The row label displayed on the left side e.g. 'Service Quality'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this row within the table (top to bottom)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, db_constraint=False, help_text='The fixed grid table this row belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tables.table')),
            ],
            options={
                'verbose_name': 'historical table row',
                'verbose_name_plural': 'historical table rows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTableColumn',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('header', models.CharField(help_text="The column header label displayed to the user e.g. 'Company Name'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this column within the table (left to right)')),
                ('is_required', models.BooleanField(default=False, help_text='Whether cells in this column must be filled in')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('column_type', models.ForeignKey(blank=True, db_constraint=False, help_text='The data type for cells in this column', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.datatype')),
                ('data_source', models.ForeignKey(blank=True, db_constraint=False, help_text='Required when column_type is dropdown or radio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.datasource')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, db_constraint=False, help_text='The table this column belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tables.table')),
            ],
            options={
                'verbose_name': 'historical table column',
                'verbose_name_plural': 'historical table columns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('header', models.CharField(help_text="The column header label displayed to the user e.g. 'Company Name'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this column within the table (left to right)')),
                ('is_required', models.BooleanField(default=False, help_text='Whether cells in this column must be filled in')),
                ('column_type', models.ForeignKey(help_text='The data type for cells in this column', on_delete=django.db.models.deletion.CASCADE, related_name='table_columns', to='data.datatype')),
                ('data_source', models.ForeignKey(blank=True, help_text='Required when column_type is dropdown or radio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_columns', to='data.datasource')),
                ('table', models.ForeignKey(help_text='The table this column belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tables.table')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('row_label', models.CharField(help_text="The row label displayed on the left side e.g. 'Service Quality'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this row within the table (top to bottom)')),
                ('table', models.ForeignKey(help_text='The fixed grid table this row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tables.table')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTableCellConfig',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cell_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional override for the cell data type. If blank the column type is used.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.datatype')),
                ('data_source', models.ForeignKey(blank=True, db_constraint=False, help_text='Required when cell_type overrides to dropdown or radio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.datasource')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, db_constraint=False, help_text='The fixed grid table this cell config belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tables.table')),
                ('column', models.ForeignKey(blank=True, db_constraint=False, help_text='The column this cell sits in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tables.tablecolumn')),
                ('row', models.ForeignKey(blank=True, db_constraint=False, help_text='The row this cell sits in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tables.tablerow')),
            ],
            options={
                'verbose_name': 'historical table cell config',
                'verbose_name_plural': 'historical table cell configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TableCellConfig',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cell_type', models.ForeignKey(help_text='Optional override for the cell data type. If blank the column type is used.', on_delete=django.db.models.deletion.CASCADE, related_name='cell_configs', to='data.datatype')),
                ('data_source', models.ForeignKey(blank=True, help_text='Required when cell_type overrides to dropdown or radio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_configs', to='data.datasource')),
                ('table', models.ForeignKey(help_text='The fixed grid table this cell config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cell_configs', to='tables.table')),
                ('column', models.ForeignKey(help_text='The column this cell sits in', on_delete=django.db.models.deletion.CASCADE, related_name='cell_configs', to='tables.tablecolumn')),
                ('row', models.ForeignKey(help_text='The row this cell sits in', on_delete=django.db.models.deletion.CASCADE, related_name='cell_configs', to='tables.tablerow')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'abstract': False,
                'unique_together': {('table', 'row', 'column')},
            },
        ),
    ]
