# Generated by Django 6.0.3 on 2026-03-18 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTableCellConfig',
            new_name='HistoricalTableCell',
        ),
        migrations.RenameModel(
            old_name='TableCellConfig',
            new_name='TableCell',
        ),
        migrations.AlterModelOptions(
            name='historicaltablecell',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical table cell', 'verbose_name_plural': 'historical table cells'},
        ),
    ]
