# Generated by Django 6.0.3 on 2026-03-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_historicaltablecellconfig_historicaltablecell_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltablecell',
            old_name='cell_type',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='historicaltablecolumn',
            old_name='column_type',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='tablecell',
            old_name='cell_type',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='tablecolumn',
            old_name='column_type',
            new_name='data_type',
        ),
    ]
