# Generated by Django 5.2.4 on 2026-03-11 19:38

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email_host', models.CharField(help_text='The SMTP server address (e.g., smtp.gmail.com).', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_host_user', models.CharField(max_length=255, unique=True)),
                ('email_host_password_encrypted', models.CharField(blank=True, max_length=500, null=True)),
                ('default_system_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='EMAIL USE TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='EMAIL USE SSL')),
                ('send_email', models.BooleanField(default=True, help_text='Send emails when checked; test mode when unchecked.', verbose_name='Enable Email Sending')),
            ],
            options={
                'ordering': ['-updated', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalMailConfig',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('email_host', models.CharField(help_text='The SMTP server address (e.g., smtp.gmail.com).', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_host_user', models.CharField(db_index=True, max_length=255)),
                ('email_host_password_encrypted', models.CharField(blank=True, max_length=500, null=True)),
                ('default_system_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='EMAIL USE TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='EMAIL USE SSL')),
                ('send_email', models.BooleanField(default=True, help_text='Send emails when checked; test mode when unchecked.', verbose_name='Enable Email Sending')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mail config',
                'verbose_name_plural': 'historical mail configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
