# Generated by Django 5.2.2 on 2025-06-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(help_text='The SMTP server address (e.g., smtp.gmail.com).', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_host_user', models.CharField()),
                ('email_host_password', models.CharField()),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_system_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='EMAIL USE TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='EMAIL USE SSL')),
                ('send_email', models.BooleanField(default=True, help_text='Send emails when checked; test mode when unchecked.', verbose_name='Enable Email Sending')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
