# Generated by Django 6.0.3 on 2026-03-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailconfig',
            name='default_from_email',
        ),
    ]
